config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users

  resources :plants do
    collection do
      get 'mes-plantes'
    end
    resources :bookings, except: [:new] do
      resources :reviews, only: [:create]
    end
  end

  resources :bookings, only: [:index, :update, :destroy]


  # Static pages
  get 'about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :plant

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :plant
  has_one_attached :image
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  belongs_to :user
  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: [:name],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :plant
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :plant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plants
  has_many :reservations
  validates :username, presence: true, uniqueness: true

  # Add devise modules and omniauth for Facebook login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :password])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def my_bookings
    @bookings = Booking.where(plant: current_user.plants)
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(booking_params)
    @booking.plant = @plant
    @booking.user = current_user
    @diff_in_days = @booking.end_date - @booking.start_date
    @total_price = ((@diff_in_days * @plant.price) + 7)
    @booking.total_price = @total_price

    if @booking.save!
      redirect_to bookings_path, notice: "Votre plante est réservée !"
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy!
      redirect_to bookings_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @plants = Plant.all
  end

  def about
  end

  def login
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @plant = Plant.find(params[:plant_id])
    @photo = @plant.photos.build(photo_params)
    if @photo.save
      redirect_to @plant, notice: 'Photo added successfully.'
    else
      redirect_to @plant, alert: 'Could not add the photo.'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to @photo.plant, notice: 'Photo removed successfully.'
  end

  private

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_plant, only: [:show, :edit, :update]

  def index
    if params[:query].present?
      @plants = Plant.search_by_name(params[:query])
    else
      @plants = Plant.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = current_user.plants.build(plant_params)
    if @plant.save
      redirect_to mes_plantes_plants_path, notice: 'Plante ajoutée à la location !'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @plant.update(plant_params)
      redirect_to mes_plantes_plants_path, notice: 'Votre plante a été modifiée'
    else
      render :edit
    end
  end

  def destroy
    @plant = Plant.find(params[:format])
    if @plant.destroy!
      redirect_to mes_plantes_plants_path, notice: 'Votre plante a été supprimée'
    end
  end

  def book
    @reservation = @plant.reservations.build(user: current_user)
    if @reservation.save
      ReservationMailer.with(user: current_user, plant: @plant).booking_email.deliver_later
      redirect_to @plant, notice: 'Plant booked successfully.'
    else
      redirect_to @plant, alert: 'Could not book the plant.'
    end
  end

  def mes_plantes
    @plants = Plant.where(user: current_user)
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:name, :description, :price, :photo, :query)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations
  end

  def my_reservations
    @reservations = Reservation.where(plant: current_user.plants)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @plant = Plant.find(params[:plant_id])
    @review = @plant.reviews.build(review_params.merge(user: current_user))
    if @review.save
      redirect_to @plant, notice: 'Review added successfully.'
    else
      redirect_to @plant, alert: 'Could not add the review.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="reservation-container">
  <div class="reservation-header">Mes Réservations</div>
  <% if @bookings.any? %>
    <% @bookings.each do | booking | %>
    <div class="reservation-card">
        <%= cl_image_tag booking.plant.photo.key,style: 'max-height: 250px; object-fit: crop;' %>
        <div class="reservation-details">
            <h3 class="reservation-title"><%= booking.plant.name %></h3>
            <p>Date: <%= booking.created_at %> </p>
            <p>Loué du : <%= booking.start_date %> au <%= booking.end_date %></p>
            <p>En location par : <%= booking.plant.user.username %>
            <p>Total : <%= booking.total_price %> €</p>
            <%= button_to 'Annuler la réservation', booking_path(booking), class:"sweetalert", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Etes-vous sur ?"} %>
        </div>
    </div>
    <% end %>
  <% else %>
  <div class="reservation-card p-5 mt-4 d-flex justify-content-center">
    <p class="mb-0 pb-5">Pas de réservation pour le moment</p>
  </div>
  <% end %>
</div>

app/views/bookings/my_bookings.html.erb
<h1>Bookings#my_bookings</h1>
<p>Find me in app/views/bookings/my_bookings.html.erb</p>

app/views/layouts/_footer.html.erb
  <footer class="container-fluid mt-2" style="max-width:100vw!important;">
    <div class="row" style="max-width:100vw;">
      <div class="col-md-3 mb-4">
        <div class="footer-logo">
          <img src="<%=image_path('logo.png')%>" alt="AirPlant Logo" class="img-fluid">
          <p>Reconnectez vos espaces à la nature, avec style.</p>
          <div class="google-rating">
            <span>Google </span>
            <span>★★★★★</span>
            <span>4,5/5</span>
          </div>
        </div>
      </div>

      <div class="col-md-3 mb-4">
        <h5>Végétalisez</h5>
        <ul class="list-unstyled">
          <li><%= link_to "Je loue", new_plant_path, class: "nav-link text-decoration-none text-dark" %></li>
          <li><a href="#" class="text-decoration-none text-dark">Entretien</a></li>
          <li><%= link_to 'À propos', about_path, class: 'nav-link text-decoration-none text-dark' %></li>
          <li><a href="#" class="text-decoration-none text-dark">Location de plantes</a></li>
        </ul>
      </div>

      <div class="col-md-3 mb-4">
        <h5>Louez</h5>
        <ul class="list-unstyled">
          <li><a href="#" class="text-decoration-none text-dark">Location événementielle</a></li>
          <li><a href="#" class="text-decoration-none text-dark">Location annuelle</a></li>
        </ul>
      </div>

      <div class="col-md-3 mb-4">
        <h5>Contactez-nous</h5>
        <ul class="list-unstyled">
          <li><%= link_to 'Paris', plants_path, class: 'nav-link text-decoration-none text-dark' %></li>
          <li><a href="#" class="text-decoration-none text-dark">Bordeaux</a></li>
          <li><a href="#" class="text-decoration-none text-dark">Marseille</a></li>
        </ul>
      </div>
    </div>

  <div class="footer-bottom text-center py-3">
    <div class="social-links mb-3">
      <a href="#"><i class="fab fa-instagram me-2"></i></a>
      <a href="#"><i class="fab fa-pinterest me-2"></i></a>
      <a href="#"><i class="fab fa-linkedin me-2"></i></a>
    </div>
    <p class="mb-">© 2024 Tous droits réservés - AirPlant.fr</p>
    <p class="mb-0">
      <a href="#" class="me-2 text-dark">Conditions générales de vente</a> |
      <a href="#" class="text-dark">Mentions légales</a>
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", style: "width: 80px; height: 30px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="input-group w-50">
        <%= form_with url: plants_path, class:"d-flex position-relative search-center", method: :get, local: true do %>
          <%= text_field_tag :query, params[:query], placeholder:"Rechercher une plante", class:"form-control"%>
          <%= button_tag(type: "submit", class: "btn btn-success text-white d-flex") do %>
              Chercher <i class="fas fa-search me-2 ps-2 pt-1"></i>
          <% end %>
        <% end %>
      </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Je loue", new_plant_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">Blog</a>
          </li>
          <li class="nav-item">
            <%= link_to 'À propos', about_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.palasa.co.in/cdn/shop/articles/15_Top_Indoor_Plants_That_are_Perfect_for_Small_Spaces.jpg?v=1694781533&width=360", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes plantes", mes_plantes_plants_path, class: "dropdown-item" %>
              <%= link_to "Editer le profil ", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="#" class="nav-link link-dark">Blog</a>
          </li>
          <li class="nav-item">
            <%= link_to 'À propos', about_path, class: 'nav-link link-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPlant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'devise/shared/flashes' %>
    <%= render "/layouts/navbar" %>
    <%= yield %>
    <%= render "/layouts/footer" %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", style: "width: 80px; height: 30px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><a href="#" class="nav-link px-2 link-dark">LOCATION DE PLANTES</a></li>
      <li><a href="#" class="nav-link px-2 link-dark">ENTRETIEN</a></li>
      <li><a href="#" class="nav-link px-2 link-dark">BLOG</a></li>
      <li><a href="#" class="nav-link px-2 link-dark">CONTACT</a></li>
    </ul>


<div class="container my-4">
    <div class="input-group">
      <input class="form-control" type="text" name="search[query]" placeholder="Entrez votre Ville" id="search_query">
      <button name="button" type="submit" class="btn btn-primary d-flex align-items-center">
        <i class="fas fa-search me-2"></i>
        <span>Search</span>
      </button>
    </div>
  </div>
  <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes reservations", reservations_path, class: "nav-link" %>
          </li>


          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Actions", "#", class: "dropdown-item" %>
              <%= link_to "Mes plantes", plants_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://36vine.com/wp-content/uploads/2023/12/aa83f2ab7561ac20f6a4b07ac336eaa8.webp);">
  <div class="container">
    <h1>Louer vos plantes grace à AirPlant</h1>
  </div>
</div>

<h2 class="text-center mt-3 mb-3">Top villes</h2>
<div class="cards">
  <%= link_to plants_path, class: 'card-category-link text-decoration-none' do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1524396309943-e03f5249f002?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    Paris
  </div>
<% end %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.musement.com/cover/0001/44/la-bourse-in-bordeaux-the-water-mirror-by-night-jpg_header-43181.jpeg?w=1200&h=630&q=95&fit=crop)">
    Bordeaux
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.marseille.fr/sites/default/files/styles/custom_poster_768x529/public/contenu/mairie/vue-generale-de-marseille_1920x600.jpg?itok=pMsl9Rvw)">
    Marseille
  </div>
</div>
<h2 class="text-center mt-3 mb-3">Top plantes</h2>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://m.media-amazon.com/images/I/81TJpwrDY8L._AC_UF1000,1000_QL80_.jpg)">
    Géranium
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.ctfassets.net/b85ozb2q358o/3YnA2pLFdMDnr3rx4KdCtQ/a1bf618906fba92504876d609cd043ab/comment-entretenir-les-cactus-et-plantes-grasses-5.jpg)">
    Cactus
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1490080410551-72586d706202?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
    Sapin
  </div>
</div>

app/views/plants/_form.html.erb
<h1>form plants</h1>

app/views/plants/about.html.erb
<h1>Pages about</h1>

app/views/plants/edit.html.erb
<div class="w-50 mx-auto mb-5">
  <h1 class="text-center mt-3">Modifiez votre annonce</h1>
  <%= simple_form_for(@plant, url: plant_path(@plant), method: :patch) do |f| %>
    <div class="form-inputs">
      <%= f.input :name, label: "Nom de la plante" %>
      <%= f.input :description, label: "Description" %>
      <%= f.input :price, label: "Votre prix pour une journée" %>
      <%= f.input :photo, as: :file, label: "Photo" %>
    </div>

    <div class="form-actions d-flex justify-content-center">
      <%= f.button :submit, "Modifier", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/plants/index.html.erb
 <main>
<% if params[:query].present? %>
    <section class="py-5 text-center plante-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1521334884684-d80222895322?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGxhbnQlMjBpbnRlcmlvcnxlbnwwfDB8MHx8fDA%3D);">
    <div class="row py-lg-5 w-75 m-auto">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-lighter text-white">Trouvez la plante idéale pour votre idée</h1>
        <p class="lead text-white">Retrouvez toutes les plantes nécéssaires pour votre intérieur ou vos évènements. Changez en quelques heures toute la décoration pour épater vos proches et vos invités.</p>
      </div>
    </div>
  </section>
   <% else %>
  <section class="py-5 text-center plante-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1476595461800-421569e956f6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    <div class="row py-lg-5 w-75 m-auto">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-lighter text-white">Découvrez les plantes Parisiennes</h1>
        <p class="lead text-white">Du géranium au petit cactus retrouvez tous les plantes nécéssaires pour votre intérieur ou vos évènements. Changez en quelques heures toute la décoration pour épater vos proches et vos invités.</p>
      </div>
    </div>
  </section>
<% end %>

  <div class="main-container d-flex">
    <div class="cards mt-3">
      <% @plants.each do | plant | %>
        <div class="card">
          <%= cl_image_tag plant.photo.key, style: 'max-height: 250px; object-fit: crop;' %>
            <div class="card-body">
              <h5 class="card-title"><%= plant.name %></h5>
              <p class="card-text fw-lighter text-muted fs-6"><%= plant.description %></p>
              <div class="d-flex justify-content-between align-items-center align-middle">
              <p class="mt-3"><%= plant.price %> €/Jour</p>
              <%= link_to "Voir détails", plant_path(plant), class:"btn btn-success border-0 text-white" %>
              </div>
            </div>
        </div>
      <% end %>
    </div>
<% if params[:query].present? %>
      <img id="map" class="d-none" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/600x1000?access_token=pk.eyJ1IjoibG91aXNjYW5vIiwiYSI6ImNseGx3ZzR2eDAxdzUybXNiNDBoMGx4NjUifQ.eVWGXr64VQyknMtuQrKjAg'>
<% else %>
<img id="map" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/600x1000?access_token=pk.eyJ1IjoibG91aXNjYW5vIiwiYSI6ImNseGx3ZzR2eDAxdzUybXNiNDBoMGx4NjUifQ.eVWGXr64VQyknMtuQrKjAg'>
 <% end %>

  </div>
</main>

app/views/plants/mes_plantes.html.erb
<div class="reservation-container">
  <% if @plants.any? %>
    <div class="reservation-header">Mes plantes en location</div>
    <% @plants.each do |plant| %>
      <div class="reservation-card">
        <%= cl_image_tag plant.photo.key,style: 'max-height: 250px; object-fit: crop;' %>
        <div class="reservation-details">
          <h3 class="reservation-title"><%= plant.name %></h3>
          <p>Description: <%= plant.description %></p>
          <p>Prix : <%= plant.price %> €</p>
          <%= link_to 'Modifier', edit_plant_path(plant), class: 'btn btn-success' %>
          <%= button_to 'Supprimer', mes_plantes_plants_path(plant), method: :delete, data: { turbo_confirm: 'Voulez-vous supprimer cette plante?' }, class: 'btn btn-danger sweetalert' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="reservation-header">Mes plantes en location</div>
    <div class="reservation-card p-5 mt-4 d-flex justify-content-center">
      <div class="reservation-details">
        <p class="mb-0 pb-5">Aucune plante disponible pour le moment.</p>
      </div>
    </div>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="w-50 mx-auto mb-5">
<h1 class="text-center mt-3">Louez votre plante !</h1>
<%= simple_form_for(@plant) do |f| %>
    <div class="form-inputs">
      <%= f.input :name, label:"Nom de la plante" %>
      <%= f.input :description %>
      <%= f.input :price, label:"Votre prix pour une journée" %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions d-flex justify-content-center">
      <%= f.button :submit, "Ajouter", class: "btn btn-success" %>
    </div>
<% end %>
</div>

app/views/plants/show.html.erb
<div class="mb-5 w-75 mx-auto">
  <%= link_to "< Retour", plants_path, class:"text-decoration-none text-black mb-3 mt-2" %>
  <%= cl_image_tag @plant.photo.key, class: "rounded mt-3 mb-3 img-fluid mx-auto d-block" %>

    <div class="row">
      <div class="col-8">
        <div class="card card-body mb-3">
          <h2><%= @plant.name %></h2>
          <p><small><%= @plant.description %></small></p>
          <p><small>En location par : <%= @plant.user.username %></small></p>
        </div>
      </div>

          <div class="border p-3 rounded col-4" data-controller="booking" data-booking-price-value="<%= @plant.price %>">
            <p class='fw-bold fs-3'><%= @plant.price %>€ <small class='fw-light'>jour</small></p>
            <%= simple_form_for([@plant, @booking], html: { class: 'confirmation-form' }) do |f| %>
              <div class="d-flex flex-column">
                <%= f.input :start_date, label: "Début", as: :string, input_html: { data: { controller: "datepicker", action: "change->booking#update", booking_target: "start_date" } }, id: 'booking_form_start_date' %>
                <%= f.input :end_date, label: "Fin", as: :string, input_html: { data: { controller: "datepicker", action: "change->booking#update", booking_target: "end_date" } }, id: 'booking_form_end_date' %>
                <p data-booking-target='info'></p>
                <p><strong>Frais de réservation: 2 €</strong></p>
                <p><strong>Entretien: 5 €</strong></p>
                <p class='fw-bold' data-booking-target='total_price'></p>
                <%= f.submit 'Réserver', class: 'btn btn-success w-100 text-white' %>
              </div>
            <% end %>
        </div>
      </div>

app/views/reservations/my_reservations.html.erb
<h1>my reservations</h1>